### ISSUE TITLE
Selecting enough options from multi custom component, will misplace the dropdown button

### ISSUE THREAD

**Issue by vcalexa** [Greentube/ngx-typeahead#12]
From the Multi custom typeahead component choose Skiing, Snowboarding Movies and Hiking.

![typeahead_dropdown_button](https://user-images.githubusercontent.com/25703463/32775238-2cb51d06-c92f-11e7-8c70-601a6b494c47.png)

**Comment by meeroslav** [comment]
This should be taken care of with external component styles.
