### ISSUE TITLE
Multiple dropdowns opened all at once

### ISSUE THREAD

**Issue by vcalexa** [Greentube/ngx-typeahead#2]
Trying to open a second dropdown while a first dropdown is expanded should not result in 2 overlapping dropdown lists.

![typeahead_multiple_drops](https://user-images.githubusercontent.com/25703463/32720895-25e3e0b8-c865-11e7-9fc0-d1a5fe39eb42.png)

**Comment by meeroslav** [comment]
So, this scenario happens if the expand arrows are being used.
