### ISSUE TITLE
Lack of vertical space between badges inside type-ahead

### ISSUE THREAD

**Issue by joaopgrassi** [Greentube/ngx-typeahead#25]
In a type-ahead that contains several items, it's missing some vertical spacing between then. The image below demonstrates the issue:

![image](https://user-images.githubusercontent.com/5938087/38136572-8d37e3ec-341f-11e8-82fa-94d3fa084b9e.png)

**Comment by meeroslav** [comment]
Since it's using Bootstrap I believe this should be solved in the separate styles.
