### ISSUE TITLE
The demo is down

### ISSUE THREAD

**Issue by marfnk** [Greentube/ngx-typeahead#27]
https://greentube.github.io/ngx-typeahead/
gives a 404 Page Not Found Error

**Comment by joaopgrassi** [comment]
Hi @marfnk, thanks for reporting. I'll look into it.

**Comment by joaopgrassi** [comment]
Hi @marfnk 
Fixed. Please refer to the new url: https://greentube.github.io/ngx-typeahead/demo.
Thanks again for reporting!
