### ISSUE TITLE
Single-fixed and multi-fixed components remove selection when space key is pressed

### ISSUE THREAD

**Issue by vcalexa** [Greentube/ngx-typeahead#5]
Steps to reproduce:
1. Select any option from the single fixed component(e.g. Skiing)
2. Press the space key once
3. Click anywhere outside the component

Actual behavior: the initial selection is removed
Expected: Space key should have no effect

This also occurs on the multi-fixed component

**Comment by meeroslav** [comment]
This is actually trimming of space on focus-out
